<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EN911371" ignored="0" name="ChromeTests" tests="3" failures="1" timestamp="2020-09-07T16:35:49 COT" time="36.809" errors="0">
  <testcase name="applyFilter" time="10.75" classname="com.endava.tests.SearchProductTest"/>
  <testcase name="addToBasket" time="13.281" classname="com.endava.tests.BasketTest"/>
  <testcase name="setPrices" time="7.096" classname="com.endava.tests.SearchProductTest">
    <failure type="java.lang.AssertionError" message="The price exceeds the limits expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The price exceeds the limits expected [true] but found [false]
at com.endava.tests.SearchProductTest.setPrices(SearchProductTest.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- setPrices -->
</testsuite> <!-- ChromeTests -->
